# stack build plan using GHC 9.14
# https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.14

packages:
- hledger-lib
- hledger
- hledger-ui
- hledger-web

compiler: ghc-9.14
resolver: nightly-2026-09-01

extra-deps: []
