{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell   #-}
{-# LANGUAGE ViewPatterns      #-}

module Hledger.Cli.Commands.Rewrite (
  rewritemode
 ,rewrite
)
where

import Control.Monad (unless)
import Data.Either (partitionEithers)
import Data.Functor.Identity
import Data.List (dropWhileEnd, sortOn)
import Data.Map qualified as M
import Data.Maybe (isJust)
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.IO qualified as T
import Hledger
import Hledger.Cli.CliOptions
import Hledger.Cli.Commands.Print
import System.Console.CmdArgs.Explicit
import System.IO (hPutStr, stderr)
import Text.Megaparsec hiding (pos1)
import Text.Printf (printf)
import Data.Algorithm.DiffContext qualified as D
import Text.PrettyPrint (render, text)

rewritemode = hledgerCommandMode
  $(embedFileRelative "Hledger/Cli/Commands/Rewrite.txt")
  [flagReq ["add-posting"] (\s opts -> Right $ setopt "add-posting" s opts) "'ACCT  AMTEXPR'"
           "add a posting to ACCT, which may be parenthesised. AMTEXPR is either a literal amount, or *N which means the transaction's first matched amount multiplied by N (a decimal number). Two spaces separate ACCT and AMTEXPR."
  ,flagNone ["diff"] (setboolopt "diff") "generate diff suitable as an input for patch tool"
  ,flagNone ["verbose-tags"] (setboolopt "verbose-tags") "add tags indicating generated/modified data"
  ,layoutFlag
  ]
  cligeneralflagsgroups1
  hiddenflags
  ([], Just $ argsFlag "[QUERY] --add-posting \"ACCT  AMTEXPR\" ...")

-- TODO regex matching and interpolating matched name in replacement
-- TODO interpolating match groups in replacement
-- TODO allow using this on unbalanced entries, eg to rewrite while editing

rewrite opts@CliOpts{rawopts_=rawopts,reportspec_=rspec} j@Journal{jtxns=ts} = do
  -- rewrite matched transactions
  let
    today = _rsDay rspec
    verbosetags = boolopt "verbose-tags" rawopts
    modifiers = transactionModifierFromOpts opts : jtxnmodifiers j
  let j' = j{jtxns=either error' id $ modifyTransactions (journalAccountType j) (journalInheritedAccountTags j) mempty (queryExpandCurAliases j) today verbosetags modifiers ts}  -- PARTIAL:
  -- run the print command, showing all transactions, or show diffs
  printOrDiff rawopts opts{reportspec_=rspec{_rsQuery=Any}} j j'

-- | Build a 'TransactionModifier' from any query arguments and --add-posting flags
-- provided on the command line, or throw a parse error.
transactionModifierFromOpts :: CliOpts -> TransactionModifier
transactionModifierFromOpts CliOpts{rawopts_=rawopts} =
    TransactionModifier{tmquerytxt=q, tmpostingrules=ps}
  where
    q = T.pack . unwords . map quoteIfNeeded $ listofstringopt "args" rawopts
    ps = map (parseposting . T.pack) $ listofstringopt "add-posting" rawopts
    parseposting t = either (error' . errorBundlePretty) id ep  -- PARTIAL:
      where
        ep = runIdentity (runJournalParser (tmpostingrulep Nothing <* eof) t')
        t' = " " <> t <> "\n" -- inject space and newline for proper parsing

printOrDiff :: RawOpts -> (CliOpts -> Journal -> Journal -> IO ())
printOrDiff opts
    | boolopt "diff" opts = const (diffOutput (layoutFromRawOpts opts))
    | otherwise = flip (const print')

-- | How many lines of unchanged context to show around each change,
-- as with diff -U3. patch and similar tools need some context to be
-- able to apply a patch.
diffContextLines :: Int
diffContextLines = 3

-- | A replacement of a source file's lines [start..end) with new lines.
type Edit = (Int, Int, [Text])

-- | Show the changes between two journals as a unified diff, suitable
-- for piping to patch.
--
-- Only transactions which exist as journal entries in a file can be
-- patched. Changed transactions which don't - ones generated from CSV
-- or timeclock data, or by a periodic transaction rule - are left out
-- of the diff, and reported on stderr.
diffOutput :: PostingLayout -> Journal -> Journal -> IO ()
diffOutput postinglayout j j' = do
    unless (null unpatchable) . hPutStr stderr $ unpatchableWarning unpatchable
    T.putStr . foldMap fileDiff $ M.toAscList editsbyfile
  where
    changed = [(transactionWithMostlyOriginalPostings t, transactionWithMostlyOriginalPostings t')
              | (t, t') <- zip (jtxns j) (jtxns j'), t /= t']
    -- collected per file, in no particular order; fileDiff sorts them
    (edits, unpatchable) = partitionEithers $ map txnEdit changed
    editsbyfile = M.fromListWith (++) edits

    -- The rewriting of a changed transaction, as a replacement of its lines in
    -- its source file; or, if it has no journal entry to replace, why not.
    txnEdit (t, t')
      -- A transaction generated by a periodic rule occupies no lines of its own;
      -- its source position is the rule's, which we must not overwrite.
      | isJust . lookup generatedTransactionTagName $ ttags t =
          Right "generated by a periodic transaction rule"
      -- Transactions read from CSV or timeclock data have a source line but no line range.
      | (SourcePos fp line _, SourcePos _ line' _) <- tsourcepos t, line' > line =
          Left (fp, [(unPos line, unPos line', newlines)])
      | otherwise = Right . T.pack $ "read from " <> sourceName (fst $ tsourcepos t)
      where
        -- showTransaction* adds a trailing blank line; the source lines don't include one.
        newlines = dropWhileEnd T.null . T.lines $ showTransactionWithLayout postinglayout t'

    fileDiff (fp, es) = case lookup fp $ jfiles j of
      Nothing -> ""
      Just contents -> unifiedDiff fp oldlines $ applyEdits (sortOn first3 es) oldlines
        where oldlines = T.lines contents

-- | Explain which changed transactions were left out of the diff, and why.
unpatchableWarning :: [Text] -> String
unpatchableWarning reasons = unlines $
     printf "warning: %d changed transaction%s not shown in the diff, having no journal entry to patch:"
       n (if n == (1::Int) then " is" else "s are" :: String)
   : [printf "  %d %s" howmany reason | (reason, howmany) <- M.toAscList reasoncounts]
  where
    n = length reasons
    reasoncounts = M.fromListWith (+) [(T.unpack r, 1::Int) | r <- reasons]

-- | Replace line ranges in a list of lines. Edits are expected to be
-- sorted by start line and non-overlapping; any that aren't are skipped.
applyEdits :: [Edit] -> [Text] -> [Text]
applyEdits = go 1
  where
    go _ [] ls = ls
    go lineno ((start, end, new):es) ls
      | start < lineno || end < start = go lineno es ls
      | otherwise                     = before <> new <> go end es (drop (end-start) rest)
      where (before, rest) = splitAt (start-lineno) ls

-- | Render the differences between two versions of a file's lines as a
-- unified diff, with the standard amount of context. Returns the empty
-- text if there are no differences.
unifiedDiff :: FilePath -> [Text] -> [Text] -> Text
unifiedDiff fp old new
  | null hunks = ""
  | otherwise  = T.pack . render $ D.prettyContextDiff (text fp) (text fp) (text . T.unpack . D.unnumber) hunks
  where hunks = D.getContextDiff (Just diffContextLines) old new
