#!/usr/bin/env bash
# hledger2shelltest SCRIPT
#
# Speaking generally: given an executable hashbang script (beginning with #!/usr/bin/env),
# this generates a similarly-named shelltestrunner test that will repeatably
# run the same command as the script and test its (stderr) output.
# (Ideally, this would be built in to shelltestrunner.)
# More precisely, this generates a test expecting no stdout, the given stderr,
# and an error exit code, for scripts reproducing various hledger errors.
#
# The script is run once to capture its output, which is then adjusted
# for use in a shelltest regex matcher:
# - file paths are simplified
# - common regex metacharacters are escaped
# - any remaining problematic text is sanitised
# - the regex is trimmed to <= 300 chars, to avoid a shelltestrunner limitation.
#
# The result is a first draft, usually needing some manual editing,
# eg to loosen wording-sensitive lines with .* or to restore a truncated ending.

SCRIPT="$1"
TEST=$(echo "$SCRIPT" | sed -E 's/\.[^.]+$//').test

{
# Commands not starting with hledger are indented, so that shelltest -w leaves them alone.
head -1 "$SCRIPT" | sed -E -e "s%#!/usr/bin/env -S +(.*[^ ]) *$%\$ \1 $SCRIPT%" -e '/^\$ hledger /!s/^\$ /$  /'
printf ">2 /"
./"$SCRIPT" 2>&1 | sed -E \
  -e 's%[^ (]*/\./%PATHPREFIX%g' \
  -e 's/\./\\./g' \
  -e 's/\^/\\^/g' \
  -e 's/\$/\\$/g' \
  -e 's/\+/\\+/g' \
  -e 's/\*/\\*/g' \
  -e 's/\?/\\?/g' \
  -e 's/\{/\\{/g' \
  -e 's/\}/\\}/g' \
  -e 's/\[/\\[/g' \
  -e 's/\]/\\]/g' \
  -e 's/\(/\\(/g' \
  -e 's/\)/\\)/g' \
  -e 's/\|/\\|/g' \
  -e 's%/%\\/%g' \
  -e 's%PATHPREFIX%.*%g' \
  | head -c 300 \
  | sed -E '$ s/([^\\])\\$/\1/'  # don't leave a dangling escape at the cut
printf "/\n>= 1\n"
} >"$TEST"
